name: e_books_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.0.1
  firebase_storage: ^11.0.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4
  image_picker_web: ^3.1.1
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  webview_flutter: ^3.0.0
  url_launcher: ^6.1.14
  uuid: ^4.2.1
#  pdfx: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
